package Views;

import Controllers.PanelRegresoListener;
import java.awt.CardLayout;

public class MenuPrincipal extends javax.swing.JFrame implements PanelRegresoListener {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();

        // Añade el mainPanel al cardsContainer con un nombre único
        cardsContainer.add(mainPanel, "MenuPrincipal");

        // Creación e inicialización de otros paneles
        ParticipantesPanel participantesPanel = new ParticipantesPanel();
        CreditosPanel creditosPanel = new CreditosPanel();

        participantesPanel.setRegresoListener(this);
        creditosPanel.setRegresoListener(this);

        cardsContainer.add(participantesPanel, "Participantes");
        cardsContainer.add(creditosPanel, "Creditos");
    }

    @Override
    public void onRegreso() {
        CardLayout card = (CardLayout) cardsContainer.getLayout();
        card.show(cardsContainer, "MenuPrincipal");
    }

    public interface PanelRegresoListener {

        void onRegreso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsContainer = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ParticipantesBtn = new javax.swing.JButton();
        CreditosBtn = new javax.swing.JButton();
        SalirBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake");
        setBackground(new java.awt.Color(194, 252, 253));
        setForeground(new java.awt.Color(194, 252, 253));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1112, 720));
        setResizable(false);

        cardsContainer.setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(194, 252, 253));
        mainPanel.setPreferredSize(new java.awt.Dimension(1112, 720));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/MenuPrincipal/Snake.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 1166));
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 557, 720));

        ParticipantesBtn.setBackground(new java.awt.Color(27, 177, 174));
        ParticipantesBtn.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        ParticipantesBtn.setForeground(new java.awt.Color(20, 20, 20));
        ParticipantesBtn.setText("Participantes");
        ParticipantesBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ParticipantesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ParticipantesBtn.setFocusable(false);
        ParticipantesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParticipantesBtnActionPerformed(evt);
            }
        });
        mainPanel.add(ParticipantesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 330, 60));

        CreditosBtn.setBackground(new java.awt.Color(27, 177, 174));
        CreditosBtn.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        CreditosBtn.setForeground(new java.awt.Color(20, 20, 20));
        CreditosBtn.setText("Créditos");
        CreditosBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreditosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreditosBtn.setFocusable(false);
        CreditosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosBtnActionPerformed(evt);
            }
        });
        mainPanel.add(CreditosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 330, 60));

        SalirBtn.setBackground(new java.awt.Color(27, 177, 174));
        SalirBtn.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        SalirBtn.setForeground(new java.awt.Color(20, 20, 20));
        SalirBtn.setText("Salir");
        SalirBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirBtn.setFocusable(false);
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });
        mainPanel.add(SalirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 330, 60));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 50)); // NOI18N
        jLabel2.setText("Campeonato Snake");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 41, 510, 58));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(86, 150, 52));
        jLabel3.setText("Campeonato Snake");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 510, 58));

        cardsContainer.add(mainPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cardsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cardsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        System.exit(0); // Termina el programa
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void CreditosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosBtnActionPerformed
        CardLayout card = (CardLayout) cardsContainer.getLayout();
        card.show(cardsContainer, "Creditos");
    }//GEN-LAST:event_CreditosBtnActionPerformed

    private void ParticipantesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParticipantesBtnActionPerformed
        CardLayout card = (CardLayout) cardsContainer.getLayout();
        card.show(cardsContainer, "Participantes");
    }//GEN-LAST:event_ParticipantesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreditosBtn;
    private javax.swing.JButton ParticipantesBtn;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JPanel cardsContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
