package Views;

import Models.Participante;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import Controllers.DatabaseManager;
import Controllers.Main;
import java.awt.HeadlessException;

public class RegistrarParticipanteFrame extends javax.swing.JFrame {

    Participante participante;

    /**
     * Creates new form RegistrarParticipante
     */
    public RegistrarParticipanteFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        sobrenombreLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sobrenombreTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        apellidosTxt = new javax.swing.JTextField();
        apellidosLbl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cedulaTxt = new javax.swing.JTextField();
        cedulaLbl = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        emailTxt = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        fechaNacLbl = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        residenciaTxt = new javax.swing.JTextField();
        residenciaLbl = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        nombreTxt = new javax.swing.JTextField();
        nombreLbl = new javax.swing.JLabel();
        registrarBtn = new javax.swing.JButton();
        anioSpinner = new javax.swing.JSpinner();
        diaSpinner = new javax.swing.JSpinner();
        mesSpinner = new javax.swing.JSpinner();

        jSeparator8.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField8.setBackground(new java.awt.Color(0, 255, 102));
        jTextField8.setBorder(null);
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel9.setText("Nombre:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloLbl.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        tituloLbl.setText("Registro de nuevo participante");
        jPanel1.add(tituloLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        sobrenombreLbl.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        sobrenombreLbl.setText("Sobrenombre:");
        jPanel1.add(sobrenombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 100, 40));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 280, 10));

        sobrenombreTxt.setBackground(new java.awt.Color(0, 255, 102));
        sobrenombreTxt.setBorder(null);
        sobrenombreTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(sobrenombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 280, 40));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 280, 10));

        apellidosTxt.setBackground(new java.awt.Color(0, 255, 102));
        apellidosTxt.setBorder(null);
        apellidosTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(apellidosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 280, 40));

        apellidosLbl.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        apellidosLbl.setText("Apellidos:");
        jPanel1.add(apellidosLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 40));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 280, 10));

        cedulaTxt.setBackground(new java.awt.Color(0, 255, 102));
        cedulaTxt.setBorder(null);
        cedulaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cedulaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 280, 40));

        cedulaLbl.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        cedulaLbl.setText("Cédula:");
        jPanel1.add(cedulaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 40));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 280, 10));

        emailTxt.setBackground(new java.awt.Color(0, 255, 102));
        emailTxt.setBorder(null);
        emailTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 280, 40));

        emailLbl.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        emailLbl.setText("Email:");
        jPanel1.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 40));

        fechaNacLbl.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        fechaNacLbl.setText("Nacimiento:");
        jPanel1.add(fechaNacLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 120, 40));

        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 280, 10));

        residenciaTxt.setBackground(new java.awt.Color(0, 255, 102));
        residenciaTxt.setBorder(null);
        residenciaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(residenciaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 280, 40));

        residenciaLbl.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        residenciaLbl.setText("Residencia:");
        jPanel1.add(residenciaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 100, 40));

        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 280, 10));

        nombreTxt.setBackground(new java.awt.Color(0, 255, 102));
        nombreTxt.setBorder(null);
        nombreTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 280, 40));

        nombreLbl.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        nombreLbl.setText("Nombre:");
        jPanel1.add(nombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 40));

        registrarBtn.setText("Registrar");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 160, 40));
        jPanel1.add(anioSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 110, 30));
        jPanel1.add(diaSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 60, 30));
        jPanel1.add(mesSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        try {
            String nombre = nombreTxt.getText();
            String apellidos = apellidosTxt.getText();
            String cedula = cedulaTxt.getText();
            String email = emailTxt.getText();
            String residencia = residenciaTxt.getText();
            String sobrenombre = sobrenombreTxt.getText();

            // Asegúrate de que ninguno de los campos esté vacío
            if (nombre.isEmpty() || apellidos.isEmpty() || cedula.isEmpty()
                    || email.isEmpty() || residencia.isEmpty() || sobrenombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Obtener la fecha de nacimiento
            int dia = (Integer) diaSpinner.getValue();
            int mes = (Integer) mesSpinner.getValue();
            int anio = (Integer) anioSpinner.getValue();

            int codigo = 0;

            LocalDate fechaNacimiento = LocalDate.of(anio, mes, dia);
            this.participante = new Participante(nombre, apellidos, cedula, email, residencia, sobrenombre, fechaNacimiento, codigo);
            // TODO Base de datos
            int codigoGenerado = DatabaseManager.agregarParticipante(participante);

            // Mostrar el código en un JOptionPane
            JOptionPane.showMessageDialog(this, "El código de participante es: " + codigoGenerado, "Código de Registro", JOptionPane.INFORMATION_MESSAGE);

            JOptionPane.showMessageDialog(this, "Participante registrado con éxito", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            // TODO guardar en la lista local
            Main.listaParticipantes.agregar(participante);

            // TODO enviar correo con num aleatorio
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar el participante: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();

    }//GEN-LAST:event_registrarBtnActionPerformed

    public Participante getParticipante() {
        return participante;
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner anioSpinner;
    private javax.swing.JLabel apellidosLbl;
    private javax.swing.JTextField apellidosTxt;
    private javax.swing.JLabel cedulaLbl;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JSpinner diaSpinner;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel fechaNacLbl;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JSpinner mesSpinner;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JLabel residenciaLbl;
    private javax.swing.JTextField residenciaTxt;
    private javax.swing.JLabel sobrenombreLbl;
    private javax.swing.JTextField sobrenombreTxt;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
