package Views;

import Controllers.PanelRegresoListener;
import Models.ListaDoblementeEnlazada;
import Models.Resultado;
import javax.swing.table.DefaultTableModel;

public class ResultadosPanel extends javax.swing.JPanel {


    private PanelRegresoListener listener;
    private ListaDoblementeEnlazada<Resultado> listaResultados;

    /**
     * Creates new form ParticipantesFrame
     *
     * @param listaResultados
     */
    public ResultadosPanel(ListaDoblementeEnlazada<Resultado> listaResultados) {
        initComponents();
        this.listaResultados = listaResultados;
        actualizarTablaResultados();

        regresarBtn.addActionListener((java.awt.event.ActionEvent e) -> {
            if (listener != null) {
                listener.onRegreso(); // Llamar al método onRegreso de la interfaz
            }
        });
    }

    // Método para establecer el listener
    public void setRegresoListener(PanelRegresoListener listener) {
        this.listener = listener;
    }

    void actualizarTablaResultados() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Participante");
        modelo.addColumn("Puntuación");
        modelo.addColumn("Fecha y Hora de Inicio");
        modelo.addColumn("Fecha y Hora de Fin");
        modelo.addColumn("Duración (segundos)");

        for (Resultado resultado : listaResultados.getLista()) {
            modelo.addRow(new Object[]{
                resultado.getParticipante().getSobrenombre(),
                resultado.getPuntuacion(),
                resultado.getFechaHoraInicio(),
                resultado.getFechaHoraFin(),
                resultado.getDuracionEnSegundos()
            });
            System.out.println(resultado);
        }

        resultadosTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarBtn = new javax.swing.JButton();
        resultsScrollPane = new javax.swing.JScrollPane();
        resultadosTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1112, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regresarBtn.setText("Regresar a menú");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 170, 40));

        resultadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Participante", "Puntuación", "Fecha y Hora de Inicio", "Fecha y Hora de Fin", "Duración (segundos)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        resultsScrollPane.setViewportView(resultadosTable);

        add(resultsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Resources/SnakeBackground.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1150, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JTable resultadosTable;
    private javax.swing.JScrollPane resultsScrollPane;
    // End of variables declaration//GEN-END:variables
}
